default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: eunny_rails_db

test:
  <<: *default
  database: eunny_rails_db_test

production:
  <<: *default

  primary: &primary_production
    <<: *default
    database: market_link_production
    username: market_link
    password: <%= ENV["MARKET_LINK_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: market_link_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: market_link_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: market_link_production_cable
    migrations_paths: db/cable_migrate
