default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: eunny_rails_db

test:
  <<: *default
  database: eunny_rails_db_test

production:
  <<: *default

  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>

  queue:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>

  cable:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>